# Generated by Django 3.2 on 2021-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colB', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teste',
            },
        ),
    ]
