# Generated by Django 3.2.1 on 2021-05-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paginas', '0002_delete_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
