# Generated by Django 3.2.1 on 2021-05-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_testetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteB',
            fields=[
                ('alfa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('beta', models.CharField(max_length=50)),
            ],
        ),
    ]
