# Generated by Django 3.2.1 on 2021-06-25 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='COMPRADOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_nomeComprador', models.CharField(max_length=50, null=True)),
                ('comp_estado', models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('ES', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('PR', 'Paraná'), ('GO', 'Goias'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('DF', 'Distrito Federal'), ('BA', 'Bahia'), ('SE', 'Sergipe'), ('AL', 'Alagoas'), ('PE', 'Pernambuco'), ('PB', 'Paraíba'), ('RN', 'Rio Grande do Norte'), ('CE', 'Ceará'), ('PI', 'Piau'), ('MA', 'Maranhão'), ('PA', 'Pará'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('AC', 'Acre'), ('RR', 'Roraima'), ('RO', 'Rondonia')], max_length=50)),
                ('comp_cnpj', models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('ES', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('PR', 'Paraná'), ('GO', 'Goias'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('DF', 'Distrito Federal'), ('BA', 'Bahia'), ('SE', 'Sergipe'), ('AL', 'Alagoas'), ('PE', 'Pernambuco'), ('PB', 'Paraíba'), ('RN', 'Rio Grande do Norte'), ('CE', 'Ceará'), ('PI', 'Piau'), ('MA', 'Maranhão'), ('PA', 'Pará'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('AC', 'Acre'), ('RR', 'Roraima'), ('RO', 'Rondonia')], max_length=50)),
                ('comp_codigoSap', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GERENCIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gere_nome', models.CharField(max_length=50)),
                ('gere_grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LEILAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leil_nome', models.CharField(max_length=50)),
                ('leil_dataResultadoLeilao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LOTE',
            fields=[
                ('lote_lote', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lote_proprietario', models.CharField(choices=[('Petrobras', 'Petrobras'), ('Consorcio', 'Consorcio')], max_length=50)),
                ('lote_al', models.CharField(max_length=50)),
                ('lote_ano', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)])),
                ('lote_alienacaoAutorizada', models.CharField(choices=[('Alienar', 'Alienar'), ('Não Autorizado', 'Não Autorizado')], max_length=50)),
                ('lote_isaRetirada', models.CharField(max_length=50)),
                ('lote_dataRetirada', models.DateField()),
                ('lote_quantidadeFoto', models.BigIntegerField()),
                ('lote_valorContabilUnitario', models.FloatField(null=True)),
                ('lote_valorContabilTotal', models.FloatField(null=True)),
                ('lote_valorReposicaoUnitario', models.FloatField(null=True)),
                ('lote_valorTotalReposicao', models.FloatField(null=True)),
                ('lote_valorComparacaoVMA', models.FloatField(null=True)),
                ('lote_vmaUnitario', models.FloatField(null=True)),
                ('lote_vmaTotal', models.FloatField(null=True)),
                ('lote_localArmazenamento', models.CharField(max_length=50, null=True)),
                ('lote_isaSipa', models.CharField(max_length=50, null=True)),
                ('lote_dataSipa', models.DateField(null=True)),
                ('lote_tipoVenda', models.CharField(choices=[('Sucateamento', 'Sucateamento'), ('Vendido', 'Vendido'), ('', '')], max_length=50, null=True)),
                ('lote_isaEnvioArm', models.CharField(max_length=50, null=True)),
                ('lote_dataEnvoArm', models.DateField()),
                ('lote_gerencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.gerencia')),
                ('lote_leilao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.leilao')),
                ('lote_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MATERIAL',
            fields=[
                ('mate_cod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mate_descricao', models.CharField(max_length=50, null=True)),
                ('mate_ncm', models.CharField(max_length=50, null=True)),
                ('mate_grupoMercadoria', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TESTES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testeA', models.CharField(max_length=50, null=True)),
                ('testeB', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LOTE_DET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lode_centroAtual', models.CharField(max_length=50, null=True)),
                ('lode_elementoPep', models.CharField(max_length=50, null=True)),
                ('lode_deposito', models.CharField(max_length=50, null=True)),
                ('lode_tipoAvaliacao', models.CharField(max_length=50, null=True)),
                ('lode_loteNm', models.CharField(max_length=50, null=True)),
                ('lode_numeroSerie', models.CharField(max_length=50, null=True)),
                ('lode_quantidadeOriginal', models.FloatField(null=True)),
                ('lode_quantidadeRetiradaDip', models.FloatField(null=True)),
                ('lode_quantidadeNaoLocalizada', models.FloatField(null=True)),
                ('lode_quantidadeAtual', models.FloatField(null=True)),
                ('lode_unidade', models.CharField(max_length=50, null=True)),
                ('lode_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.lote')),
                ('lode_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.material')),
            ],
        ),
        migrations.CreateModel(
            name='HIST_LOTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hist_tipoAlteracao', models.CharField(max_length=50)),
                ('hist_coluna', models.CharField(max_length=50)),
                ('hist_dadoAnterior', models.CharField(max_length=50)),
                ('hist_dadoNovo', models.CharField(max_length=50)),
                ('hist_lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.lote')),
                ('hist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DISPUTA_ABERTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diab_comunicadoVendaEnviado', models.CharField(max_length=50, null=True)),
                ('diab_valorVendaLanceTotal', models.FloatField(null=True)),
                ('diab_valorVendaSab', models.FloatField(null=True)),
                ('diab_prazoPagamento', models.FloatField(null=True)),
                ('diab_dataPagamento', models.DateField()),
                ('diab_valorPago', models.FloatField(null=True)),
                ('diab_email', models.CharField(max_length=50, null=True)),
                ('diab_telefone', models.CharField(max_length=50, null=True)),
                ('diab_comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.comprador')),
                ('diab_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.lote')),
            ],
        ),
    ]
