# Generated by Django 3.2.1 on 2021-05-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GERENCIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gere_nome', models.CharField(max_length=50)),
                ('gere_grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LOTE',
            fields=[
                ('lote_lote', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lote_al', models.CharField(max_length=50)),
                ('lote_centro', models.CharField(max_length=50)),
                ('lote_elementoPep', models.CharField(max_length=50, null=True)),
                ('lote_deposito', models.CharField(max_length=50, null=True)),
                ('lote_tipoVenda', models.CharField(max_length=50, null=True)),
                ('lote_alienacaoAutorizada', models.CharField(max_length=50, null=True)),
                ('lote_superbid', models.CharField(max_length=200, null=True)),
                ('lote_quantidadeFoto', models.BigIntegerField()),
                ('lote_localArmazenamento', models.CharField(max_length=50, null=True)),
                ('lote_fase', models.CharField(max_length=50)),
                ('lote_dataSipa', models.DateField()),
                ('lote_dataEnvioLotesLeilao', models.DateField()),
                ('lote_dataSolicitacaoLeilao', models.DateField()),
                ('lote_dataResultadoLeilao', models.DateField()),
                ('lote_gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.gerencia')),
            ],
        ),
    ]
