# Generated by Django 3.2.1 on 2021-05-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LOTE',
        ),
    ]
