# Generated by Django 3.2.1 on 2021-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='lote_ano',
            field=models.BigIntegerField(default=2020),
            preserve_default=False,
        ),
    ]
