# Generated by Django 3.2.1 on 2021-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='lote_dataEnvoArm',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_dataRetirada',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_isaRetirada',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_quantidadeFoto',
            field=models.BigIntegerField(null=True),
        ),
    ]
