# Generated by Django 3.2.1 on 2021-06-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20210628_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='lote_alienacaoAutorizada',
            field=models.CharField(choices=[('Autorizada', 'Autorizada'), ('Não Autorizado', 'Não Autorizado')], max_length=50),
        ),
    ]
