# Generated by Django 3.2.1 on 2021-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_lote_lote_alienacaoautorizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='lote_dataRetirada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
