# Generated by Django 3.2.1 on 2021-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='lote_alientacaoAutorizada',
        ),
        migrations.AddField(
            model_name='lote',
            name='lote_alienacaoAutorizada',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_deposito',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_elementoPep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_localArmazenamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_superbid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_tipoVenda',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
