# Generated by Django 3.2.1 on 2021-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20210526_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='MATERIAL',
            fields=[
                ('mate_cod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mate_descricao', models.CharField(max_length=50, null=True)),
                ('mate_ncm', models.CharField(max_length=50, null=True)),
                ('mate_grupoMercadoria', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
