# Generated by Django 3.2.1 on 2021-05-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOTE_HIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lohi_tipoAvaliacao', models.CharField(max_length=50, null=True)),
                ('lohi_quantidadeOriginal', models.FloatField(null=True)),
                ('lohi_quantidadeRetiradaDip', models.FloatField(null=True)),
                ('lohi_quantidadeNaoLocalizada', models.FloatField(null=True)),
                ('lohi_quantidadeAtual', models.FloatField(null=True)),
                ('lohi_unidade', models.CharField(max_length=50, null=True)),
                ('lohi_dipSipa', models.FloatField(null=True)),
                ('lohi_retirada', models.FloatField(null=True)),
                ('lohi_valorContabilUnitario', models.FloatField(null=True)),
                ('lohi_valorContabilTotal', models.FloatField(null=True)),
                ('lohi_valorReposicaoUnitario', models.FloatField(null=True)),
                ('lohi_valorTotalReposicao', models.FloatField(null=True)),
                ('lohi_valorComparacaoVMA', models.FloatField(null=True)),
                ('lohi_vmaUnitario', models.FloatField(null=True)),
                ('lohi_vmaTotal', models.FloatField(null=True)),
                ('lohi_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.lote')),
                ('lohi_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.material')),
            ],
        ),
    ]
