# Generated by Django 3.2.1 on 2021-06-30 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0004_alter_lote_lote_dataretirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='lote_dataEnvoArm',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_dataSipa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_isaEnvioArm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_isaRetirada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_isaSipa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_leilao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.leilao'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_localArmazenamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_quantidadeFoto',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_tipoVenda',
            field=models.CharField(blank=True, choices=[('Sucateamento', 'Sucateamento'), ('Vendido', 'Vendido'), ('', '')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_valorComparacaoVMA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_valorContabilTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_valorContabilUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_valorReposicaoUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_valorTotalReposicao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_vmaTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_vmaUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
