# Generated by Django 3.2.1 on 2021-05-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_lote_his'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote_his',
            name='lohi_dipSipa',
        ),
    ]
