# Generated by Django 3.2.1 on 2021-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20210630_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='lote_dataRetirada',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lote_isaRetirada',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lote_valorComparacaoVMA',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lote_valorContabilTotal',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lote_valorContabilUnitario',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lote_valorReposicaoUnitario',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lote_valorTotalReposicao',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lote_vmaTotal',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='lote_vmaUnitario',
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_dataRetirada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_isaRetirada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_valorComparacaoVMA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_valorContabilTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_valorContabilUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_valorReposicaoUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_valorTotalReposicao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_vmaTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote_det',
            name='lode_vmaUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
