# Generated by Django 3.2.1 on 2021-07-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20210701_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote_det',
            name='lode_valorContabilTotalAtual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
