# Generated by Django 3.2.1 on 2021-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_remove_lote_his_lohi_dipsipa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote_his',
            name='lohi_retirada',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
