# Generated by Django 3.2.1 on 2021-07-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_lote_det_lode_valorcontabiltotalatual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote_det',
            name='lode_centroAtual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_deposito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_elementoPep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_loteNm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_numeroSerie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_quantidadeAtual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_quantidadeNaoLocalizada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_quantidadeOriginal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_quantidadeRetiradaDip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_tipoAvaliacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote_det',
            name='lode_unidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
