# Generated by Django 3.2.1 on 2021-07-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_auto_20210701_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist_lote',
            name='hist_dataAlteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
