# Generated by Django 3.2.1 on 2021-07-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_hist_lote_hist_dataalteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_lote',
            name='hist_dataAlteracao',
            field=models.DateTimeField(editable=False),
        ),
    ]
