# Generated by Django 3.2.1 on 2021-07-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_alter_hist_lote_hist_dataalteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist_lote',
            name='hist_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.lote_det'),
        ),
    ]
