# Generated by Django 3.2.1 on 2021-07-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_hist_lote_hist_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_lote',
            name='hist_dadoAnterior',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hist_lote',
            name='hist_dadoNovo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
