# Generated by Django 3.2.1 on 2021-08-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_auto_20210809_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_dataPagamento',
            field=models.DateField(null=True),
        ),
    ]
