# Generated by Django 3.2.1 on 2021-08-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0015_alter_disputa_aberta_diab_datapagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='lote_vmaLote',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
