# Generated by Django 3.2.1 on 2021-08-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0017_lote_det_lode_vmapercentuallote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputa_aberta',
            name='diab_email',
        ),
        migrations.RemoveField(
            model_name='disputa_aberta',
            name='diab_telefone',
        ),
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_comunicadoVendaEnviado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_dataPagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_lanceTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_lanceUnitario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_prazoPagamento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_valorPago',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_valorVendaLanceTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disputa_aberta',
            name='diab_valorVendaSab',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
