# Generated by Django 3.2.7 on 2021-11-18 21:30

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0018_auto_20210831_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACOMP_BUCKET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_descricao', models.CharField(max_length=500)),
                ('bucket_datacriacao', models.DateTimeField(auto_now_add=True)),
                ('bucket_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote_tipoVenda',
            field=models.CharField(blank=True, choices=[('Sucateamento', 'Sucateamento'), ('Vendido', 'Vendido'), ('Leilao', 'Leilão'), ('', '')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sumary', ckeditor.fields.RichTextField(blank=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ACOMP_TAREFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa_nome', models.CharField(max_length=100)),
                ('tarefa_anotacoes', models.CharField(max_length=500)),
                ('tarefa_Criador', models.IntegerField()),
                ('tarefa_datacriacao', models.DateTimeField()),
                ('tarefa_dtinicio', models.DateField(null=True)),
                ('tarefa_dtconclusao', models.DateField(null=True)),
                ('tarefa_prioridade', models.CharField(choices=[('Urgente', 'Urgente'), ('Importante', 'Importante'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Importante', max_length=25)),
                ('tarefa_progresso', models.CharField(choices=[('Não iniciada', 'Não iniciada'), ('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída')], default='Não iniciada', max_length=25)),
                ('tarefa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.acomp_bucket')),
                ('tarefa_responsavel_cod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ACOMP_COMENTARIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_descricao', models.CharField(max_length=500, null=True)),
                ('coment_datacriacao', models.DateTimeField(auto_now_add=True)),
                ('coment_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coment_tarefa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.acomp_tarefa')),
            ],
        ),
    ]
