# Generated by Django 3.2.7 on 2021-11-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0019_auto_20211118_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomp_tarefa',
            name='tarefa_datacriacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
