# Generated by Django 3.2.7 on 2021-11-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0020_alter_acomp_tarefa_tarefa_datacriacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomp_tarefa',
            name='tarefa_dtalteracao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='postagem',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registros.acomp_tarefa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('cor', models.CharField(choices=[('Vermelho Vivo ', 'Vermelho Vivo'), ('Vermelho Claro', 'Vermelho Claro'), ('Rosa claro', 'Rosa claro'), ('Amarelo', 'Amarelo'), ('Bronze', 'Bronze'), ('Laranja', 'Laranja'), ('Pêssego', 'Pêssego'), ('Margarida', 'Margarida'), ('Verde', 'Verde'), ('Verde Claro', 'Verde Claro'), ('Verde Lima', 'Verde Lima'), ('Verde Azulado', 'Verde Azulado'), ('Verde Escuro', 'Verde Escuro'), ('Azul', 'Azul'), ('Azul Claro', 'Claro'), ('Azul Piscina', 'Azul Piscina'), ('Roxo', 'Roxo'), ('Lavanda', 'Lavanda'), ('Ameixa', 'Ameixa'), ('Cinza', 'Cinza'), ('Cinza Claro', 'Cinza Claro'), ('Cinza Escuro', 'Cinza Escuro'), ('Marrom', 'Marrom')], max_length=255, null=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.acomp_tarefa')),
            ],
        ),
    ]
