# Generated by Django 3.2.7 on 2021-11-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0022_alter_acomp_tarefa_tarefa_anotacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomp_tarefa',
            name='tarefa_atrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acomp_tarefa',
            name='tarefa_lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.lote'),
        ),
        migrations.AlterField(
            model_name='acomp_tarefa',
            name='tarefa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.acomp_bucket'),
        ),
    ]
