# Generated by Django 3.2.7 on 2021-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0024_alter_acomp_tarefa_tarefa_dtalteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomp_tarefa',
            name='tarefa_dtalteracao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
