# Generated by Django 3.2.7 on 2021-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0025_alter_acomp_tarefa_tarefa_dtalteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acomp_tarefa',
            name='tarefa_lote',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
